import {Metadata} from "next";

const metadata: Metadata = {
    title: "İletişim",
    description: "Generated by create next app",
}

export default function Home() {
    return (
        <div>
            <h1>İletişim sayfası</h1>
        </div>
    )
}